name: Test deploy                    # Workflow 이름
on:                                  # Event 감지
  push:
    branches:
      - main                        
jobs:                                # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v3

      - name: Check Node v            # Node v 확인
        run: node -v
        
      # - name: Install dependencies    # 의존 파일 설치
      #   run: npm install
      
      # - name: Generate build          # React Build
      #   run: npm run build
      # - name: Bucket list
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: us-east-1

      #   run: |
      #     aws s3api list-buckets --endpoint-url https://29c6e4b55b1ddb8d2b6e69df21141caa.r2.cloudflarestorage.com/ci-cd
      - name: discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: >
            The project ${{ github.repository }} has been deployed.\n
            - Repo: ${{ github.repository }}\n
            - Message: ${{ github.event.head_commit.message }}\n
            - Commit: ${{ github.sha }}\n
            - Author: ${{ github.actor }}\n
            - Action: ${{ github.action }}\n
            - Event Name: ${{ github.event_name }}\n
            - Ref: ${{ github.ref }}\n
            - Workflow: ${{ github.workflow }}\n
            - Job: ${{ github.job }}\n
            - Took: (You'll need another step to calculate this)
              
      # - name: slack
      #   uses: 8398a7/action-slack@v3.15.1
      #   with:
      #     status: ${{ job.status }}
      #     author_name: React CI
      #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL }}
      #   if: always()
      # - name: Sync Bucket
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: us-east-1
      #   run: |
      #     aws s3 cp build s3://ci-cd \
      #       --endpoint-url https://29c6e4b55b1ddb8d2b6e69df21141caa.r2.cloudflarestorage.com/ \
      #       # --recursive \
